### ISSUE TITLE
Where did all my custom admonitions go?

### ISSUE THREAD

**Issue by gudstrand** [valentine195/obsidian-admonition#154] opened 2022-01-16 16:38 UTC
I had created around 8-10 custom admonitions that I use in several notes, including my daily note template. When I created my daily note this AM I noticed all the admonitions were displaying as nothing more than text. I went to the config page for my admonitions and they are all gone?

Where are the custom admonitions defined? I use git to back up my vault and I hope that I can recover them from there.

**Comment by valentine195** [comment] 2022-01-16 20:19
They are defined in `<VAULT>/.obsidian/plugins/obsidian-admonition/data.json`

**Comment by gudstrand** [comment] 2022-01-16 23:21
Thanks! I was able to restore them from a previous backup.

**Comment by valentine195** [comment] 2022-02-04 16:39
Closing this issue… it was likely caused by a sync issue or the plugin’s data saving file operation being interrupted.

**Closed by valentine195** 2022-02-04 16:39 UTC
