### ISSUE TITLE
Collapsible by Default doesn't work

### ISSUE THREAD

**Issue by jakeoung** [valentine195/obsidian-admonition#41] opened 2021-06-05 21:47 UTC
First of all, huge thanks for the amazing plugin. Recently, I observe that Collapsible by Default doesn't work anymore. Maybe it is because I upgrade to v0.12.4. Do you have any idea or if you need any information, please let me know!

**Comment by BricoleurSoul** [comment] 2021-06-05 21:52
Just came here to say same thing. **After v0.12.4it definitely doesn't work** but I can't be sure if it was that particular release as I have updated several times since last actually working with the collapse as 90% of time I use viewing with default ion open.

**Comment by valentine195** [comment] 2021-06-05 21:53
Thanks - I see the issue (unintentional consequence of #39), should be able to fix it once I can sit at my computer.

**Comment by valentine195** [comment] 2021-06-06 00:42
Please try 5.0.1 and let me know if the issue is still occurring.

**Comment by BricoleurSoul** [comment] 2021-06-06 01:23
Perfect!  issued resolved.
Thanks for such a quick turnaround. 
I really  don’t know what I would do without it when working on a large document now.
I greatly appreciate your effort on this one!

**Comment by valentine195** [comment] 2021-06-06 01:25
Great, thanks!

Glad you enjoy the plugin! Let me know if there's any additional features you'd like to see 😁

Going to close this issue since it has been resolved.

**Closed** 2021-06-06 01:25 UTC
